name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Android Project အပြည့်အစုံကို Auto Re-create လုပ်ခြင်း
      - run: |
          rm -rf android pubspec.yaml
          flutter create . --platforms=android --org=com.watch.earn

      # main.dart ကို Auto ပြန်အစားထိုးခြင်း
      - run: flutter pub get

      # Debug APK Build ဆွဲခြင်း
      - run: flutter build apk --debug --no-tree-shake-icons

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
