name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter create . --platforms=android

      - run: flutter pub get
      
      # Release အစား Debug APK အဖြစ် ပြောင်းလဲဆောက်လုပ်ခြင်း
      - run: flutter build apk --debug --no-tree-shake-icons
      
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
